### ISSUE TITLE
isue

### ISSUE THREAD

**Issue by lol19093109** [KDot227/Somali-rat#4]
[2023-06-14 21:15:47] [INFO    ] discord.client: logging in using static token
[2023-06-14 21:15:47] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 394eac231581df258284fabb3dncj3873NXCja119839).
[2023-06-14 21:15:49] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\NIGGER\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\NIGGER\Downloads\Somali-rat-main (2)\Somali-rat-main\main.py", line 42, in on_ready
    guild_id = guilds[0].id
               ~~~~~~^^^
  File "C:\Users\bigdoa\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\utils.py", line 243, in __getitem__
    return self.__copied[idx]
           ~~~~~~~~~~~~~^^^^^
IndexError: list index out of range

**Comment by LocalSmail** [comment]
code sucks dk why your surprised

**Comment by LocalSmail** [comment]
these github rats barely work with more than one connection as they use a session type system which breaks due to how discords api works

**Comment by KDot227** [comment]
bros gotta keep riding 🙏

**Comment by LocalSmail** [comment]
> 

its true wym lol

**Comment by LocalSmail** [comment]
All github rats that use the session system always break over 1 connection

**Comment by KDot227** [comment]
mans mad he got kicked 😭

**Comment by LocalSmail** [comment]
jit is delusional 😭

**Comment by LocalSmail** [comment]
bet flopparware doesnt have a ring0 rootkit or even good stealth LL
